services:
  - type: web
    name: drone-club
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: ADMIN_TOKEN
        sync: false
      - key: S3_ENDPOINT
        value: https://ofrvhxwwfhjspcsrrmys.supabase.co/storage/v1/s3
      - key: S3_REGION
        value: ap-southeast-2
      - key: S3_ACCESS_KEY_ID
        value: ofrvhxwwfhjspcsrrmys
      - key: S3_SECRET_ACCESS_KEY
        sync: false
      - key: S3_BUCKET
        value: upload-files
